In [1]:
import numpy as np

In [2]:
np.__version__

'1.26.4'

In [3]:
import sys
sys.version

'3.12.7 | packaged by Anaconda, Inc. | (main, Oct  4 2024, 13:17:27) [MSC v.1929 64 bit (AMD64)]'

**Creating Arrays**


In [4]:
my_list =[0,1,2,3,4,5]
my_list

[0, 1, 2, 3, 4, 5]

In [5]:
type(my_list)

list

In [6]:
print(np.array(my_list))

[0 1 2 3 4 5]


In [10]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [17]:
np.arange(3.0)

array([0., 1., 2.])

In [15]:
np.arange(10,15)

array([10, 11, 12, 13, 14])

In [14]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [18]:
np.arange(-20,10)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,
         6,   7,   8,   9])

In [24]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [25]:
np.zeros([2,2])

array([[0., 0.],
       [0., 0.]])

In [26]:
np.zeros([10,2])

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [28]:
np.zeros([1,1])

array([[0.]])

In [30]:
np.zeros([10,2],dtype=int)

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0]])

In [31]:
n=(6,7)
n1=(6,8)
print(np.zeros(n1))

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


In [32]:
np.ones(3)

array([1., 1., 1.])

In [33]:
np.ones(3,dtype=int)

array([1, 1, 1])

In [34]:
np.ones((5,4),dtype=int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [35]:
np.twos((5,4),dtype=int)

AttributeError: module 'numpy' has no attribute 'twos'

In [36]:
np.random(5)

TypeError: 'module' object is not callable

In [37]:
np.rand(10)

AttributeError: module 'numpy' has no attribute 'rand'

In [38]:
np.rand(4)

AttributeError: module 'numpy' has no attribute 'rand'

In [39]:
np.random.rand(4)

array([0.20021477, 0.89357521, 0.12808467, 0.20208842])

In [45]:
np.random.rand(3,5)

array([[0.67958127, 0.8869928 , 0.47012407, 0.32626943, 0.82565305],
       [0.06707689, 0.86074916, 0.90092623, 0.65044764, 0.16295662],
       [0.66576749, 0.67104558, 0.15414191, 0.21523314, 0.49039132]])

In [57]:
np.random.randint(300)

98

In [63]:
np.random.randint(10,20,3)

array([11, 12, 16])

In [64]:
np.random.randint(5,15,3)

array([14, 11,  5])

In [69]:
np.random.randint(10,100,1)

array([75])

In [77]:
np.random.randint(1,100000,(2,2))

array([[79658, 59817],
       [22365, 49559]])

In [79]:
np.arange(1,13).reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [80]:
np.ndarray

numpy.ndarray

In [81]:
b =np.arange(1,13).reshape(3,4)

In [82]:
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [83]:
b[0,2]

3

In [84]:
b[0,0]

1

In [85]:
b[0,1]

2

In [86]:
b[1,2]

7

In [87]:
b[:]

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [88]:
b[1:3]

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [90]:
b[1,2]

7

In [91]:
b[1,-1]

8

**Operations**

In [92]:
from numpy import *