# Numpy Crash Course

In [1]:
import numpy as np

In [2]:
np.__version__

'1.26.4'

In [3]:
import sys 
sys.version

'3.12.7 | packaged by Anaconda, Inc. | (main, Oct  4 2024, 13:17:27) [MSC v.1929 64 bit (AMD64)]'

## Creating Arrays

In [4]:
my_list = [0,1,2,3,4,5]
my_list

[0, 1, 2, 3, 4, 5]

In [5]:
type(my_list)

list

In [7]:
my_list

[0, 1, 2, 3, 4, 5]

In [8]:
arr = np.array(my_list) 
arr

array([0, 1, 2, 3, 4, 5])

In [14]:
import numpy as np 

In [15]:
array1= np.array([1, 2, 3, 4, 5])
array2 = np.array([6, 7, 8, 9, 10]) 

In [17]:
result_addition= array1 + array2 

In [18]:
result_addition

array([ 7,  9, 11, 13, 15])

In [20]:
result_substraction = array1 - array2 
result_substraction

array([-5, -5, -5, -5, -5])

In [21]:
result_mul = array1 * array2
result_mul

array([ 6, 14, 24, 36, 50])

In [22]:
result_divide = array1 / array2
result_divide

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [24]:
import numpy as np
#create an array from python list
my_list=[1,2,3,4,5]
arr_from_list=np.array(my_list)
print(arr_from_list)

[1 2 3 4 5]


In [25]:
#Create an array from a python tuple
my_tuple =(6,7,8,9,10)
arr_from_tuple = np.array(my_tuple)
print(arr_from_tuple)

[ 6  7  8  9 10]


In [26]:
#Generate an array filled with zeros of shape(3,3)
zeros_array=np.zeros((3,3))
print(zeros_array)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [27]:
#Generate an arry fillled with ones of shape(2,4)
ones_array=np.ones((2,4))
print(ones_array)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [31]:
#Create an empty array of shape(2,3)
empty_array=np.empty((2,3))
print(empty_array)

[[6.23042070e-307 4.67296746e-307 1.69121096e-306]
 [1.60219849e-306 1.89146896e-307 7.56571288e-307]]


In [32]:
#Generate an array from 0 to 9(exclusive) with step size 2
arange_array =np.arange(0,10,2)
print(arange_array)

[0 2 4 6 8]


In [33]:
linspace_array=np.linspace(0,10,5)
print(linspace_array)

[ 0.   2.5  5.   7.5 10. ]


In [34]:
# np.reshape(), np.transpose()

arr = np.array([1,2,3,4,5,6])
reshaped_array=np.reshape(arr,(2,3))
print(reshaped_array)

[[1 2 3]
 [4 5 6]]


In [35]:
transposed_array =np.transpose(reshaped_array)
print(transposed_array)

[[1 4]
 [2 5]
 [3 6]]


In [39]:
#Concat & Split
arr1 =np.array([[1,2,2],[3,4,4]])
arr2=np.array([[5,6,5]])
concatenated_array=np.concatenate((arr1,arr2),axis=0)
print(concatenated_array)

[[1 2 2]
 [3 4 4]
 [5 6 5]]


In [40]:
split_arrays=np.split(concatenated_array,[2])
print(split_arrays)

[array([[1, 2, 2],
       [3, 4, 4]]), array([[5, 6, 5]])]


In [41]:
arr =np.array([[1,2,3],[4,5,6]])
sum_of_elements =np.sum(arr)
print("Sum of elements:",sum_of_elements)

Sum of elements: 21


In [42]:
mean_of_elements = np.mean(arr)
mean_of_elements

3.5

In [43]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
dot_product =np.dot(arr1,arr2)
dot_product

32

In [44]:
#Cross product
cross_product =np.cross(arr1,arr2)
cross_product

array([-3,  6, -3])

In [53]:
# Compute the element-wise absolute value
arr=np.array([1,-2,3])
abs_values = np.abs(arr)
abs_values

array([1, 2, 3])

In [54]:
exp_values=np.exp(arr)
exp_values

array([ 2.71828183,  0.13533528, 20.08553692])

In [55]:
arr

array([ 1, -2,  3])

In [58]:
log_values=np.log(5)
print(log_values)

1.6094379124341003


In [59]:
angles = np.array([0,np.pi/4,np.pi/2])
sin_values=np.sin(angles)
cos_values=np.cos(angles)
tan_values=np.tan(angles)
print(sin_values)
print(cos_values)
print(tan_values)

[0.         0.70710678 1.        ]
[1.00000000e+00 7.07106781e-01 6.12323400e-17]
[0.00000000e+00 1.00000000e+00 1.63312394e+16]


In [60]:
print(np.random.rand(2,2))

[[0.37514902 0.38947856]
 [0.44213244 0.61125726]]


In [61]:
print(np.random.randn(2,2))

[[ 0.23761205 -1.95122119]
 [-0.88411404  0.66149993]]


In [69]:
print(np.random.randint(1,100,size=(3,3)))

[[63 92 11]
 [52 72 26]
 [ 4 40 39]]
